{{ if eq $.Values.credentials.existingSecretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strato-webhook.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "strato-webhook.name" . }}
    chart: {{ include "strato-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  identity: "{{ $.Values.credentials.identity}}"
  password: "{{ $.Values.credentials.password}}"
{{ end }}